ALTER TABLE artists ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE genres ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE tracks ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE plays ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
