ALTER TABLE artists MODIFY id INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE genres MODIFY id INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE tracks MODIFY id INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE plays MODIFY id INTEGER NOT NULL AUTO_INCREMENT;
